CREATE DATABASE BankingCore;

USE BankingCore;

CREATE TABLE Clients (
    ClientId INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    Phone NVARCHAR(50),
    CreatedAt DATETIME2 DEFAULT SYSDATETIME()
);